version: '3'
services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    image: 01234ab909f/lab9:ebs_frontend
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "80:80"
