FROM node:alpine

WORKDIR '/app'
ENV NODE_OPTIONS=--openssl-legacy-provider

COPY package.json .

RUN npm install

# utworz katalog i nadaj uprawnienia
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

CMD ["npm", "run", "start"]